FROM node:alpine

WORKDIR '/app'
ENV NODE_OPTIONS=--openssl-legacy-provider
COPY package.json .

RUN npm config set unsafe-perm true
RUN npm install

COPY . .
RUN chmod 777 /app/node_modules

CMD ["npm", "run", "start"]